/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AiFeedRouteImport } from './routes/ai-feed'
import { Route as DataRouteImport } from './routes/data'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as TokenRouteImport } from './routes/token'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as XstocksRouteImport } from './routes/xstocks'
import { Route as AgentsSlugRouteImport } from './routes/agents.$slug'
import { Route as CoinCoinIdRouteImport } from './routes/coin.$coinId'
import { Route as MarketsIndexRouteImport } from './routes/markets.index'
import { Route as MarketsGlobalRouteImport } from './routes/markets.global'
import { Route as MarketsHotSearchesRouteImport } from './routes/markets.hot-searches'
import { Route as MarketsTrendingRouteImport } from './routes/markets.trending'
import { Route as SwapIndexRouteImport } from './routes/swap.index'
import { Route as TokenIndexRouteImport } from './routes/token.index'
import { Route as ApiAnalyticsSwapEventRouteImport } from './routes/api/analytics/swap-event'
import { Route as ApiFeedSnapshotRouteImport } from './routes/api/feed/snapshot'
import { Route as ApiMarketStatusRouteImport } from './routes/api/market/status'
import { Route as ApiSwapPriceRouteImport } from './routes/api/swap/price'
import { Route as ApiSwapQuoteRouteImport } from './routes/api/swap/quote'
import { Route as ApiSwapResolveTokenRouteImport } from './routes/api/swap/resolve-token'
import { Route as ApiSwapTokensRouteImport } from './routes/api/swap/tokens'
import { Route as MarketsRobinhoodTokenAddressRouteImport } from './routes/markets.robinhood.$tokenAddress'
import { Route as TokenChainIdAddressRouteImport } from './routes/token.$chainId.$address'
import { Route as ApiMarketCoingeckoCoinsRouteImport } from './routes/api/market/coingecko/coins'
import { Route as ApiMarketCoingeckoSearchRouteImport } from './routes/api/market/coingecko/search'
import { Route as ApiMarketCoingeckoTrendingRouteImport } from './routes/api/market/coingecko/trending'
import { Route as ApiMarketDexscreenerPairsRouteImport } from './routes/api/market/dexscreener/pairs'
import { Route as ApiMarketDexscreenerSearchRouteImport } from './routes/api/market/dexscreener/search'
import { Route as ApiMarketGeckoterminalNetworksRouteImport } from './routes/api/market/geckoterminal/networks'
import { Route as ApiMarketGmgnHotSearchesRouteImport } from './routes/api/market/gmgn/hot-searches'
import { Route as ApiMarketGmgnTrendingRouteImport } from './routes/api/market/gmgn/trending'
import { Route as ApiMarketCoingeckoChartIdRouteImport } from './routes/api/market/coingecko/chart.$id'
import { Route as ApiMarketCoingeckoCoinIdRouteImport } from './routes/api/market/coingecko/coin.$id'
import { Route as ApiMarketDexscreenerTrendingChainIdRouteImport } from './routes/api/market/dexscreener/trending.$chainId'
import { Route as ApiMarketGeckoterminalPoolsNetworkIdRouteImport } from './routes/api/market/geckoterminal/pools.$networkId'
import { Route as ApiMarketGeckoterminalTrendingNetworkIdRouteImport } from './routes/api/market/geckoterminal/trending.$networkId'
import { Route as ApiMarketDexscreenerTokenChainIdAddressRouteImport } from './routes/api/market/dexscreener/token.$chainId.$address'
import { Route as ApiMarketGeckoterminalOhlcvNetworkIdPoolAddressRouteImport } from './routes/api/market/geckoterminal/ohlcv.$networkId.$poolAddress'
import { Route as ApiMarketGeckoterminalTokenNetworkIdAddressRouteImport } from './routes/api/market/geckoterminal/token.$networkId.$address'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AiFeedRoute = AiFeedRouteImport.update({
  id: '/ai-feed',
  path: '/ai-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenRoute = TokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const XstocksRoute = XstocksRouteImport.update({
  id: '/xstocks',
  path: '/xstocks',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSlugRoute = AgentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AgentsRoute,
} as any)
const CoinCoinIdRoute = CoinCoinIdRouteImport.update({
  id: '/coin/$coinId',
  path: '/coin/$coinId',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsIndexRoute = MarketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketsRoute,
} as any)
const MarketsGlobalRoute = MarketsGlobalRouteImport.update({
  id: '/global',
  path: '/global',
  getParentRoute: () => MarketsRoute,
} as any)
const MarketsHotSearchesRoute = MarketsHotSearchesRouteImport.update({
  id: '/hot-searches',
  path: '/hot-searches',
  getParentRoute: () => MarketsRoute,
} as any)
const MarketsTrendingRoute = MarketsTrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => MarketsRoute,
} as any)
const SwapIndexRoute = SwapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SwapRoute,
} as any)
const TokenIndexRoute = TokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TokenRoute,
} as any)
const ApiAnalyticsSwapEventRoute = ApiAnalyticsSwapEventRouteImport.update({
  id: '/api/analytics/swap-event',
  path: '/api/analytics/swap-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedSnapshotRoute = ApiFeedSnapshotRouteImport.update({
  id: '/api/feed/snapshot',
  path: '/api/feed/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketStatusRoute = ApiMarketStatusRouteImport.update({
  id: '/api/market/status',
  path: '/api/market/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwapPriceRoute = ApiSwapPriceRouteImport.update({
  id: '/api/swap/price',
  path: '/api/swap/price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwapQuoteRoute = ApiSwapQuoteRouteImport.update({
  id: '/api/swap/quote',
  path: '/api/swap/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwapResolveTokenRoute = ApiSwapResolveTokenRouteImport.update({
  id: '/api/swap/resolve-token',
  path: '/api/swap/resolve-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwapTokensRoute = ApiSwapTokensRouteImport.update({
  id: '/api/swap/tokens',
  path: '/api/swap/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRobinhoodTokenAddressRoute =
  MarketsRobinhoodTokenAddressRouteImport.update({
    id: '/robinhood/$tokenAddress',
    path: '/robinhood/$tokenAddress',
    getParentRoute: () => MarketsRoute,
  } as any)
const TokenChainIdAddressRoute = TokenChainIdAddressRouteImport.update({
  id: '/$chainId/$address',
  path: '/$chainId/$address',
  getParentRoute: () => TokenRoute,
} as any)
const ApiMarketCoingeckoCoinsRoute = ApiMarketCoingeckoCoinsRouteImport.update({
  id: '/api/market/coingecko/coins',
  path: '/api/market/coingecko/coins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketCoingeckoSearchRoute =
  ApiMarketCoingeckoSearchRouteImport.update({
    id: '/api/market/coingecko/search',
    path: '/api/market/coingecko/search',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketCoingeckoTrendingRoute =
  ApiMarketCoingeckoTrendingRouteImport.update({
    id: '/api/market/coingecko/trending',
    path: '/api/market/coingecko/trending',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketDexscreenerPairsRoute =
  ApiMarketDexscreenerPairsRouteImport.update({
    id: '/api/market/dexscreener/pairs',
    path: '/api/market/dexscreener/pairs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketDexscreenerSearchRoute =
  ApiMarketDexscreenerSearchRouteImport.update({
    id: '/api/market/dexscreener/search',
    path: '/api/market/dexscreener/search',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketGeckoterminalNetworksRoute =
  ApiMarketGeckoterminalNetworksRouteImport.update({
    id: '/api/market/geckoterminal/networks',
    path: '/api/market/geckoterminal/networks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketGmgnHotSearchesRoute =
  ApiMarketGmgnHotSearchesRouteImport.update({
    id: '/api/market/gmgn/hot-searches',
    path: '/api/market/gmgn/hot-searches',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketGmgnTrendingRoute = ApiMarketGmgnTrendingRouteImport.update({
  id: '/api/market/gmgn/trending',
  path: '/api/market/gmgn/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketCoingeckoChartIdRoute =
  ApiMarketCoingeckoChartIdRouteImport.update({
    id: '/api/market/coingecko/chart/$id',
    path: '/api/market/coingecko/chart/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketCoingeckoCoinIdRoute =
  ApiMarketCoingeckoCoinIdRouteImport.update({
    id: '/api/market/coingecko/coin/$id',
    path: '/api/market/coingecko/coin/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketDexscreenerTrendingChainIdRoute =
  ApiMarketDexscreenerTrendingChainIdRouteImport.update({
    id: '/api/market/dexscreener/trending/$chainId',
    path: '/api/market/dexscreener/trending/$chainId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketGeckoterminalPoolsNetworkIdRoute =
  ApiMarketGeckoterminalPoolsNetworkIdRouteImport.update({
    id: '/api/market/geckoterminal/pools/$networkId',
    path: '/api/market/geckoterminal/pools/$networkId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketGeckoterminalTrendingNetworkIdRoute =
  ApiMarketGeckoterminalTrendingNetworkIdRouteImport.update({
    id: '/api/market/geckoterminal/trending/$networkId',
    path: '/api/market/geckoterminal/trending/$networkId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketDexscreenerTokenChainIdAddressRoute =
  ApiMarketDexscreenerTokenChainIdAddressRouteImport.update({
    id: '/api/market/dexscreener/token/$chainId/$address',
    path: '/api/market/dexscreener/token/$chainId/$address',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketGeckoterminalOhlcvNetworkIdPoolAddressRoute =
  ApiMarketGeckoterminalOhlcvNetworkIdPoolAddressRouteImport.update({
    id: '/api/market/geckoterminal/ohlcv/$networkId/$poolAddress',
    path: '/api/market/geckoterminal/ohlcv/$networkId/$poolAddress',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketGeckoterminalTokenNetworkIdAddressRoute =
  ApiMarketGeckoterminalTokenNetworkIdAddressRouteImport.update({
    id: '/api/market/geckoterminal/token/$networkId/$address',
    path: '/api/market/geckoterminal/token/$networkId/$address',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/ai-feed': typeof AiFeedRoute
  '/data': typeof DataRoute
  '/disclaimer': typeof DisclaimerRoute
  '/leaderboard': typeof LeaderboardRoute
  '/markets': typeof MarketsRouteWithChildren
  '/methodology': typeof MethodologyRoute
  '/swap': typeof SwapRouteWithChildren
  '/token': typeof TokenRouteWithChildren
  '/trending': typeof TrendingRoute
  '/watchlist': typeof WatchlistRoute
  '/xstocks': typeof XstocksRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/coin/$coinId': typeof CoinCoinIdRoute
  '/markets/global': typeof MarketsGlobalRoute
  '/markets/hot-searches': typeof MarketsHotSearchesRoute
  '/markets/trending': typeof MarketsTrendingRoute
  '/markets/': typeof MarketsIndexRoute
  '/swap/': typeof SwapIndexRoute
  '/token/': typeof TokenIndexRoute
  '/api/analytics/swap-event': typeof ApiAnalyticsSwapEventRoute
  '/api/feed/snapshot': typeof ApiFeedSnapshotRoute
  '/api/market/status': typeof ApiMarketStatusRoute
  '/api/swap/price': typeof ApiSwapPriceRoute
  '/api/swap/quote': typeof ApiSwapQuoteRoute
  '/api/swap/resolve-token': typeof ApiSwapResolveTokenRoute
  '/api/swap/tokens': typeof ApiSwapTokensRoute
  '/markets/robinhood/$tokenAddress': typeof MarketsRobinhoodTokenAddressRoute
  '/token/$chainId/$address': typeof TokenChainIdAddressRoute
  '/api/market/coingecko/coins': typeof ApiMarketCoingeckoCoinsRoute
  '/api/market/coingecko/search': typeof ApiMarketCoingeckoSearchRoute
  '/api/market/coingecko/trending': typeof ApiMarketCoingeckoTrendingRoute
  '/api/market/dexscreener/pairs': typeof ApiMarketDexscreenerPairsRoute
  '/api/market/dexscreener/search': typeof ApiMarketDexscreenerSearchRoute
  '/api/market/geckoterminal/networks': typeof ApiMarketGeckoterminalNetworksRoute
  '/api/market/gmgn/hot-searches': typeof ApiMarketGmgnHotSearchesRoute
  '/api/market/gmgn/trending': typeof ApiMarketGmgnTrendingRoute
  '/api/market/coingecko/chart/$id': typeof ApiMarketCoingeckoChartIdRoute
  '/api/market/coingecko/coin/$id': typeof ApiMarketCoingeckoCoinIdRoute
  '/api/market/dexscreener/trending/$chainId': typeof ApiMarketDexscreenerTrendingChainIdRoute
  '/api/market/geckoterminal/pools/$networkId': typeof ApiMarketGeckoterminalPoolsNetworkIdRoute
  '/api/market/geckoterminal/trending/$networkId': typeof ApiMarketGeckoterminalTrendingNetworkIdRoute
  '/api/market/dexscreener/token/$chainId/$address': typeof ApiMarketDexscreenerTokenChainIdAddressRoute
  '/api/market/geckoterminal/ohlcv/$networkId/$poolAddress': typeof ApiMarketGeckoterminalOhlcvNetworkIdPoolAddressRoute
  '/api/market/geckoterminal/token/$networkId/$address': typeof ApiMarketGeckoterminalTokenNetworkIdAddressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/ai-feed': typeof AiFeedRoute
  '/data': typeof DataRoute
  '/disclaimer': typeof DisclaimerRoute
  '/leaderboard': typeof LeaderboardRoute
  '/methodology': typeof MethodologyRoute
  '/trending': typeof TrendingRoute
  '/watchlist': typeof WatchlistRoute
  '/xstocks': typeof XstocksRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/coin/$coinId': typeof CoinCoinIdRoute
  '/markets/global': typeof MarketsGlobalRoute
  '/markets/hot-searches': typeof MarketsHotSearchesRoute
  '/markets/trending': typeof MarketsTrendingRoute
  '/markets': typeof MarketsIndexRoute
  '/swap': typeof SwapIndexRoute
  '/token': typeof TokenIndexRoute
  '/api/analytics/swap-event': typeof ApiAnalyticsSwapEventRoute
  '/api/feed/snapshot': typeof ApiFeedSnapshotRoute
  '/api/market/status': typeof ApiMarketStatusRoute
  '/api/swap/price': typeof ApiSwapPriceRoute
  '/api/swap/quote': typeof ApiSwapQuoteRoute
  '/api/swap/resolve-token': typeof ApiSwapResolveTokenRoute
  '/api/swap/tokens': typeof ApiSwapTokensRoute
  '/markets/robinhood/$tokenAddress': typeof MarketsRobinhoodTokenAddressRoute
  '/token/$chainId/$address': typeof TokenChainIdAddressRoute
  '/api/market/coingecko/coins': typeof ApiMarketCoingeckoCoinsRoute
  '/api/market/coingecko/search': typeof ApiMarketCoingeckoSearchRoute
  '/api/market/coingecko/trending': typeof ApiMarketCoingeckoTrendingRoute
  '/api/market/dexscreener/pairs': typeof ApiMarketDexscreenerPairsRoute
  '/api/market/dexscreener/search': typeof ApiMarketDexscreenerSearchRoute
  '/api/market/geckoterminal/networks': typeof ApiMarketGeckoterminalNetworksRoute
  '/api/market/gmgn/hot-searches': typeof ApiMarketGmgnHotSearchesRoute
  '/api/market/gmgn/trending': typeof ApiMarketGmgnTrendingRoute
  '/api/market/coingecko/chart/$id': typeof ApiMarketCoingeckoChartIdRoute
  '/api/market/coingecko/coin/$id': typeof ApiMarketCoingeckoCoinIdRoute
  '/api/market/dexscreener/trending/$chainId': typeof ApiMarketDexscreenerTrendingChainIdRoute
  '/api/market/geckoterminal/pools/$networkId': typeof ApiMarketGeckoterminalPoolsNetworkIdRoute
  '/api/market/geckoterminal/trending/$networkId': typeof ApiMarketGeckoterminalTrendingNetworkIdRoute
  '/api/market/dexscreener/token/$chainId/$address': typeof ApiMarketDexscreenerTokenChainIdAddressRoute
  '/api/market/geckoterminal/ohlcv/$networkId/$poolAddress': typeof ApiMarketGeckoterminalOhlcvNetworkIdPoolAddressRoute
  '/api/market/geckoterminal/token/$networkId/$address': typeof ApiMarketGeckoterminalTokenNetworkIdAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/ai-feed': typeof AiFeedRoute
  '/data': typeof DataRoute
  '/disclaimer': typeof DisclaimerRoute
  '/leaderboard': typeof LeaderboardRoute
  '/markets': typeof MarketsRouteWithChildren
  '/methodology': typeof MethodologyRoute
  '/swap': typeof SwapRouteWithChildren
  '/token': typeof TokenRouteWithChildren
  '/trending': typeof TrendingRoute
  '/watchlist': typeof WatchlistRoute
  '/xstocks': typeof XstocksRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/coin/$coinId': typeof CoinCoinIdRoute
  '/markets/global': typeof MarketsGlobalRoute
  '/markets/hot-searches': typeof MarketsHotSearchesRoute
  '/markets/trending': typeof MarketsTrendingRoute
  '/markets/': typeof MarketsIndexRoute
  '/swap/': typeof SwapIndexRoute
  '/token/': typeof TokenIndexRoute
  '/api/analytics/swap-event': typeof ApiAnalyticsSwapEventRoute
  '/api/feed/snapshot': typeof ApiFeedSnapshotRoute
  '/api/market/status': typeof ApiMarketStatusRoute
  '/api/swap/price': typeof ApiSwapPriceRoute
  '/api/swap/quote': typeof ApiSwapQuoteRoute
  '/api/swap/resolve-token': typeof ApiSwapResolveTokenRoute
  '/api/swap/tokens': typeof ApiSwapTokensRoute
  '/markets/robinhood/$tokenAddress': typeof MarketsRobinhoodTokenAddressRoute
  '/token/$chainId/$address': typeof TokenChainIdAddressRoute
  '/api/market/coingecko/coins': typeof ApiMarketCoingeckoCoinsRoute
  '/api/market/coingecko/search': typeof ApiMarketCoingeckoSearchRoute
  '/api/market/coingecko/trending': typeof ApiMarketCoingeckoTrendingRoute
  '/api/market/dexscreener/pairs': typeof ApiMarketDexscreenerPairsRoute
  '/api/market/dexscreener/search': typeof ApiMarketDexscreenerSearchRoute
  '/api/market/geckoterminal/networks': typeof ApiMarketGeckoterminalNetworksRoute
  '/api/market/gmgn/hot-searches': typeof ApiMarketGmgnHotSearchesRoute
  '/api/market/gmgn/trending': typeof ApiMarketGmgnTrendingRoute
  '/api/market/coingecko/chart/$id': typeof ApiMarketCoingeckoChartIdRoute
  '/api/market/coingecko/coin/$id': typeof ApiMarketCoingeckoCoinIdRoute
  '/api/market/dexscreener/trending/$chainId': typeof ApiMarketDexscreenerTrendingChainIdRoute
  '/api/market/geckoterminal/pools/$networkId': typeof ApiMarketGeckoterminalPoolsNetworkIdRoute
  '/api/market/geckoterminal/trending/$networkId': typeof ApiMarketGeckoterminalTrendingNetworkIdRoute
  '/api/market/dexscreener/token/$chainId/$address': typeof ApiMarketDexscreenerTokenChainIdAddressRoute
  '/api/market/geckoterminal/ohlcv/$networkId/$poolAddress': typeof ApiMarketGeckoterminalOhlcvNetworkIdPoolAddressRoute
  '/api/market/geckoterminal/token/$networkId/$address': typeof ApiMarketGeckoterminalTokenNetworkIdAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/ai-feed'
    | '/data'
    | '/disclaimer'
    | '/leaderboard'
    | '/markets'
    | '/methodology'
    | '/swap'
    | '/token'
    | '/trending'
    | '/watchlist'
    | '/xstocks'
    | '/agents/$slug'
    | '/coin/$coinId'
    | '/markets/global'
    | '/markets/hot-searches'
    | '/markets/trending'
    | '/markets/'
    | '/swap/'
    | '/token/'
    | '/api/analytics/swap-event'
    | '/api/feed/snapshot'
    | '/api/market/status'
    | '/api/swap/price'
    | '/api/swap/quote'
    | '/api/swap/resolve-token'
    | '/api/swap/tokens'
    | '/markets/robinhood/$tokenAddress'
    | '/token/$chainId/$address'
    | '/api/market/coingecko/coins'
    | '/api/market/coingecko/search'
    | '/api/market/coingecko/trending'
    | '/api/market/dexscreener/pairs'
    | '/api/market/dexscreener/search'
    | '/api/market/geckoterminal/networks'
    | '/api/market/gmgn/hot-searches'
    | '/api/market/gmgn/trending'
    | '/api/market/coingecko/chart/$id'
    | '/api/market/coingecko/coin/$id'
    | '/api/market/dexscreener/trending/$chainId'
    | '/api/market/geckoterminal/pools/$networkId'
    | '/api/market/geckoterminal/trending/$networkId'
    | '/api/market/dexscreener/token/$chainId/$address'
    | '/api/market/geckoterminal/ohlcv/$networkId/$poolAddress'
    | '/api/market/geckoterminal/token/$networkId/$address'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/ai-feed'
    | '/data'
    | '/disclaimer'
    | '/leaderboard'
    | '/methodology'
    | '/trending'
    | '/watchlist'
    | '/xstocks'
    | '/agents/$slug'
    | '/coin/$coinId'
    | '/markets/global'
    | '/markets/hot-searches'
    | '/markets/trending'
    | '/markets'
    | '/swap'
    | '/token'
    | '/api/analytics/swap-event'
    | '/api/feed/snapshot'
    | '/api/market/status'
    | '/api/swap/price'
    | '/api/swap/quote'
    | '/api/swap/resolve-token'
    | '/api/swap/tokens'
    | '/markets/robinhood/$tokenAddress'
    | '/token/$chainId/$address'
    | '/api/market/coingecko/coins'
    | '/api/market/coingecko/search'
    | '/api/market/coingecko/trending'
    | '/api/market/dexscreener/pairs'
    | '/api/market/dexscreener/search'
    | '/api/market/geckoterminal/networks'
    | '/api/market/gmgn/hot-searches'
    | '/api/market/gmgn/trending'
    | '/api/market/coingecko/chart/$id'
    | '/api/market/coingecko/coin/$id'
    | '/api/market/dexscreener/trending/$chainId'
    | '/api/market/geckoterminal/pools/$networkId'
    | '/api/market/geckoterminal/trending/$networkId'
    | '/api/market/dexscreener/token/$chainId/$address'
    | '/api/market/geckoterminal/ohlcv/$networkId/$poolAddress'
    | '/api/market/geckoterminal/token/$networkId/$address'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/ai-feed'
    | '/data'
    | '/disclaimer'
    | '/leaderboard'
    | '/markets'
    | '/methodology'
    | '/swap'
    | '/token'
    | '/trending'
    | '/watchlist'
    | '/xstocks'
    | '/agents/$slug'
    | '/coin/$coinId'
    | '/markets/global'
    | '/markets/hot-searches'
    | '/markets/trending'
    | '/markets/'
    | '/swap/'
    | '/token/'
    | '/api/analytics/swap-event'
    | '/api/feed/snapshot'
    | '/api/market/status'
    | '/api/swap/price'
    | '/api/swap/quote'
    | '/api/swap/resolve-token'
    | '/api/swap/tokens'
    | '/markets/robinhood/$tokenAddress'
    | '/token/$chainId/$address'
    | '/api/market/coingecko/coins'
    | '/api/market/coingecko/search'
    | '/api/market/coingecko/trending'
    | '/api/market/dexscreener/pairs'
    | '/api/market/dexscreener/search'
    | '/api/market/geckoterminal/networks'
    | '/api/market/gmgn/hot-searches'
    | '/api/market/gmgn/trending'
    | '/api/market/coingecko/chart/$id'
    | '/api/market/coingecko/coin/$id'
    | '/api/market/dexscreener/trending/$chainId'
    | '/api/market/geckoterminal/pools/$networkId'
    | '/api/market/geckoterminal/trending/$networkId'
    | '/api/market/dexscreener/token/$chainId/$address'
    | '/api/market/geckoterminal/ohlcv/$networkId/$poolAddress'
    | '/api/market/geckoterminal/token/$networkId/$address'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  AiFeedRoute: typeof AiFeedRoute
  DataRoute: typeof DataRoute
  DisclaimerRoute: typeof DisclaimerRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MarketsRoute: typeof MarketsRouteWithChildren
  MethodologyRoute: typeof MethodologyRoute
  SwapRoute: typeof SwapRouteWithChildren
  TokenRoute: typeof TokenRouteWithChildren
  TrendingRoute: typeof TrendingRoute
  WatchlistRoute: typeof WatchlistRoute
  XstocksRoute: typeof XstocksRoute
  CoinCoinIdRoute: typeof CoinCoinIdRoute
  ApiAnalyticsSwapEventRoute: typeof ApiAnalyticsSwapEventRoute
  ApiFeedSnapshotRoute: typeof ApiFeedSnapshotRoute
  ApiMarketStatusRoute: typeof ApiMarketStatusRoute
  ApiSwapPriceRoute: typeof ApiSwapPriceRoute
  ApiSwapQuoteRoute: typeof ApiSwapQuoteRoute
  ApiSwapResolveTokenRoute: typeof ApiSwapResolveTokenRoute
  ApiSwapTokensRoute: typeof ApiSwapTokensRoute
  ApiMarketCoingeckoCoinsRoute: typeof ApiMarketCoingeckoCoinsRoute
  ApiMarketCoingeckoSearchRoute: typeof ApiMarketCoingeckoSearchRoute
  ApiMarketCoingeckoTrendingRoute: typeof ApiMarketCoingeckoTrendingRoute
  ApiMarketDexscreenerPairsRoute: typeof ApiMarketDexscreenerPairsRoute
  ApiMarketDexscreenerSearchRoute: typeof ApiMarketDexscreenerSearchRoute
  ApiMarketGeckoterminalNetworksRoute: typeof ApiMarketGeckoterminalNetworksRoute
  ApiMarketGmgnHotSearchesRoute: typeof ApiMarketGmgnHotSearchesRoute
  ApiMarketGmgnTrendingRoute: typeof ApiMarketGmgnTrendingRoute
  ApiMarketCoingeckoChartIdRoute: typeof ApiMarketCoingeckoChartIdRoute
  ApiMarketCoingeckoCoinIdRoute: typeof ApiMarketCoingeckoCoinIdRoute
  ApiMarketDexscreenerTrendingChainIdRoute: typeof ApiMarketDexscreenerTrendingChainIdRoute
  ApiMarketGeckoterminalPoolsNetworkIdRoute: typeof ApiMarketGeckoterminalPoolsNetworkIdRoute
  ApiMarketGeckoterminalTrendingNetworkIdRoute: typeof ApiMarketGeckoterminalTrendingNetworkIdRoute
  ApiMarketDexscreenerTokenChainIdAddressRoute: typeof ApiMarketDexscreenerTokenChainIdAddressRoute
  ApiMarketGeckoterminalOhlcvNetworkIdPoolAddressRoute: typeof ApiMarketGeckoterminalOhlcvNetworkIdPoolAddressRoute
  ApiMarketGeckoterminalTokenNetworkIdAddressRoute: typeof ApiMarketGeckoterminalTokenNetworkIdAddressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-feed': {
      id: '/ai-feed'
      path: '/ai-feed'
      fullPath: '/ai-feed'
      preLoaderRoute: typeof AiFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token': {
      id: '/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xstocks': {
      id: '/xstocks'
      path: '/xstocks'
      fullPath: '/xstocks'
      preLoaderRoute: typeof XstocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$slug': {
      id: '/agents/$slug'
      path: '/$slug'
      fullPath: '/agents/$slug'
      preLoaderRoute: typeof AgentsSlugRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/coin/$coinId': {
      id: '/coin/$coinId'
      path: '/coin/$coinId'
      fullPath: '/coin/$coinId'
      preLoaderRoute: typeof CoinCoinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/': {
      id: '/markets/'
      path: '/'
      fullPath: '/markets/'
      preLoaderRoute: typeof MarketsIndexRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/markets/global': {
      id: '/markets/global'
      path: '/global'
      fullPath: '/markets/global'
      preLoaderRoute: typeof MarketsGlobalRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/markets/hot-searches': {
      id: '/markets/hot-searches'
      path: '/hot-searches'
      fullPath: '/markets/hot-searches'
      preLoaderRoute: typeof MarketsHotSearchesRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/markets/trending': {
      id: '/markets/trending'
      path: '/trending'
      fullPath: '/markets/trending'
      preLoaderRoute: typeof MarketsTrendingRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/swap/': {
      id: '/swap/'
      path: '/'
      fullPath: '/swap/'
      preLoaderRoute: typeof SwapIndexRouteImport
      parentRoute: typeof SwapRoute
    }
    '/token/': {
      id: '/token/'
      path: '/'
      fullPath: '/token/'
      preLoaderRoute: typeof TokenIndexRouteImport
      parentRoute: typeof TokenRoute
    }
    '/api/analytics/swap-event': {
      id: '/api/analytics/swap-event'
      path: '/api/analytics/swap-event'
      fullPath: '/api/analytics/swap-event'
      preLoaderRoute: typeof ApiAnalyticsSwapEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed/snapshot': {
      id: '/api/feed/snapshot'
      path: '/api/feed/snapshot'
      fullPath: '/api/feed/snapshot'
      preLoaderRoute: typeof ApiFeedSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/status': {
      id: '/api/market/status'
      path: '/api/market/status'
      fullPath: '/api/market/status'
      preLoaderRoute: typeof ApiMarketStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swap/price': {
      id: '/api/swap/price'
      path: '/api/swap/price'
      fullPath: '/api/swap/price'
      preLoaderRoute: typeof ApiSwapPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swap/quote': {
      id: '/api/swap/quote'
      path: '/api/swap/quote'
      fullPath: '/api/swap/quote'
      preLoaderRoute: typeof ApiSwapQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swap/resolve-token': {
      id: '/api/swap/resolve-token'
      path: '/api/swap/resolve-token'
      fullPath: '/api/swap/resolve-token'
      preLoaderRoute: typeof ApiSwapResolveTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swap/tokens': {
      id: '/api/swap/tokens'
      path: '/api/swap/tokens'
      fullPath: '/api/swap/tokens'
      preLoaderRoute: typeof ApiSwapTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/robinhood/$tokenAddress': {
      id: '/markets/robinhood/$tokenAddress'
      path: '/robinhood/$tokenAddress'
      fullPath: '/markets/robinhood/$tokenAddress'
      preLoaderRoute: typeof MarketsRobinhoodTokenAddressRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/token/$chainId/$address': {
      id: '/token/$chainId/$address'
      path: '/$chainId/$address'
      fullPath: '/token/$chainId/$address'
      preLoaderRoute: typeof TokenChainIdAddressRouteImport
      parentRoute: typeof TokenRoute
    }
    '/api/market/coingecko/coins': {
      id: '/api/market/coingecko/coins'
      path: '/api/market/coingecko/coins'
      fullPath: '/api/market/coingecko/coins'
      preLoaderRoute: typeof ApiMarketCoingeckoCoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/coingecko/search': {
      id: '/api/market/coingecko/search'
      path: '/api/market/coingecko/search'
      fullPath: '/api/market/coingecko/search'
      preLoaderRoute: typeof ApiMarketCoingeckoSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/coingecko/trending': {
      id: '/api/market/coingecko/trending'
      path: '/api/market/coingecko/trending'
      fullPath: '/api/market/coingecko/trending'
      preLoaderRoute: typeof ApiMarketCoingeckoTrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/dexscreener/pairs': {
      id: '/api/market/dexscreener/pairs'
      path: '/api/market/dexscreener/pairs'
      fullPath: '/api/market/dexscreener/pairs'
      preLoaderRoute: typeof ApiMarketDexscreenerPairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/dexscreener/search': {
      id: '/api/market/dexscreener/search'
      path: '/api/market/dexscreener/search'
      fullPath: '/api/market/dexscreener/search'
      preLoaderRoute: typeof ApiMarketDexscreenerSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/geckoterminal/networks': {
      id: '/api/market/geckoterminal/networks'
      path: '/api/market/geckoterminal/networks'
      fullPath: '/api/market/geckoterminal/networks'
      preLoaderRoute: typeof ApiMarketGeckoterminalNetworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/gmgn/hot-searches': {
      id: '/api/market/gmgn/hot-searches'
      path: '/api/market/gmgn/hot-searches'
      fullPath: '/api/market/gmgn/hot-searches'
      preLoaderRoute: typeof ApiMarketGmgnHotSearchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/gmgn/trending': {
      id: '/api/market/gmgn/trending'
      path: '/api/market/gmgn/trending'
      fullPath: '/api/market/gmgn/trending'
      preLoaderRoute: typeof ApiMarketGmgnTrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/coingecko/chart/$id': {
      id: '/api/market/coingecko/chart/$id'
      path: '/api/market/coingecko/chart/$id'
      fullPath: '/api/market/coingecko/chart/$id'
      preLoaderRoute: typeof ApiMarketCoingeckoChartIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/coingecko/coin/$id': {
      id: '/api/market/coingecko/coin/$id'
      path: '/api/market/coingecko/coin/$id'
      fullPath: '/api/market/coingecko/coin/$id'
      preLoaderRoute: typeof ApiMarketCoingeckoCoinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/dexscreener/trending/$chainId': {
      id: '/api/market/dexscreener/trending/$chainId'
      path: '/api/market/dexscreener/trending/$chainId'
      fullPath: '/api/market/dexscreener/trending/$chainId'
      preLoaderRoute: typeof ApiMarketDexscreenerTrendingChainIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/geckoterminal/pools/$networkId': {
      id: '/api/market/geckoterminal/pools/$networkId'
      path: '/api/market/geckoterminal/pools/$networkId'
      fullPath: '/api/market/geckoterminal/pools/$networkId'
      preLoaderRoute: typeof ApiMarketGeckoterminalPoolsNetworkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/geckoterminal/trending/$networkId': {
      id: '/api/market/geckoterminal/trending/$networkId'
      path: '/api/market/geckoterminal/trending/$networkId'
      fullPath: '/api/market/geckoterminal/trending/$networkId'
      preLoaderRoute: typeof ApiMarketGeckoterminalTrendingNetworkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/dexscreener/token/$chainId/$address': {
      id: '/api/market/dexscreener/token/$chainId/$address'
      path: '/api/market/dexscreener/token/$chainId/$address'
      fullPath: '/api/market/dexscreener/token/$chainId/$address'
      preLoaderRoute: typeof ApiMarketDexscreenerTokenChainIdAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/geckoterminal/ohlcv/$networkId/$poolAddress': {
      id: '/api/market/geckoterminal/ohlcv/$networkId/$poolAddress'
      path: '/api/market/geckoterminal/ohlcv/$networkId/$poolAddress'
      fullPath: '/api/market/geckoterminal/ohlcv/$networkId/$poolAddress'
      preLoaderRoute: typeof ApiMarketGeckoterminalOhlcvNetworkIdPoolAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/geckoterminal/token/$networkId/$address': {
      id: '/api/market/geckoterminal/token/$networkId/$address'
      path: '/api/market/geckoterminal/token/$networkId/$address'
      fullPath: '/api/market/geckoterminal/token/$networkId/$address'
      preLoaderRoute: typeof ApiMarketGeckoterminalTokenNetworkIdAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentsRouteChildren {
  AgentsSlugRoute: typeof AgentsSlugRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsSlugRoute: AgentsSlugRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface MarketsRouteChildren {
  MarketsGlobalRoute: typeof MarketsGlobalRoute
  MarketsHotSearchesRoute: typeof MarketsHotSearchesRoute
  MarketsTrendingRoute: typeof MarketsTrendingRoute
  MarketsIndexRoute: typeof MarketsIndexRoute
  MarketsRobinhoodTokenAddressRoute: typeof MarketsRobinhoodTokenAddressRoute
}

const MarketsRouteChildren: MarketsRouteChildren = {
  MarketsGlobalRoute: MarketsGlobalRoute,
  MarketsHotSearchesRoute: MarketsHotSearchesRoute,
  MarketsTrendingRoute: MarketsTrendingRoute,
  MarketsIndexRoute: MarketsIndexRoute,
  MarketsRobinhoodTokenAddressRoute: MarketsRobinhoodTokenAddressRoute,
}

const MarketsRouteWithChildren =
  MarketsRoute._addFileChildren(MarketsRouteChildren)

interface SwapRouteChildren {
  SwapIndexRoute: typeof SwapIndexRoute
}

const SwapRouteChildren: SwapRouteChildren = {
  SwapIndexRoute: SwapIndexRoute,
}

const SwapRouteWithChildren = SwapRoute._addFileChildren(SwapRouteChildren)

interface TokenRouteChildren {
  TokenIndexRoute: typeof TokenIndexRoute
  TokenChainIdAddressRoute: typeof TokenChainIdAddressRoute
}

const TokenRouteChildren: TokenRouteChildren = {
  TokenIndexRoute: TokenIndexRoute,
  TokenChainIdAddressRoute: TokenChainIdAddressRoute,
}

const TokenRouteWithChildren = TokenRoute._addFileChildren(TokenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  AiFeedRoute: AiFeedRoute,
  DataRoute: DataRoute,
  DisclaimerRoute: DisclaimerRoute,
  LeaderboardRoute: LeaderboardRoute,
  MarketsRoute: MarketsRouteWithChildren,
  MethodologyRoute: MethodologyRoute,
  SwapRoute: SwapRouteWithChildren,
  TokenRoute: TokenRouteWithChildren,
  TrendingRoute: TrendingRoute,
  WatchlistRoute: WatchlistRoute,
  XstocksRoute: XstocksRoute,
  CoinCoinIdRoute: CoinCoinIdRoute,
  ApiAnalyticsSwapEventRoute: ApiAnalyticsSwapEventRoute,
  ApiFeedSnapshotRoute: ApiFeedSnapshotRoute,
  ApiMarketStatusRoute: ApiMarketStatusRoute,
  ApiSwapPriceRoute: ApiSwapPriceRoute,
  ApiSwapQuoteRoute: ApiSwapQuoteRoute,
  ApiSwapResolveTokenRoute: ApiSwapResolveTokenRoute,
  ApiSwapTokensRoute: ApiSwapTokensRoute,
  ApiMarketCoingeckoCoinsRoute: ApiMarketCoingeckoCoinsRoute,
  ApiMarketCoingeckoSearchRoute: ApiMarketCoingeckoSearchRoute,
  ApiMarketCoingeckoTrendingRoute: ApiMarketCoingeckoTrendingRoute,
  ApiMarketDexscreenerPairsRoute: ApiMarketDexscreenerPairsRoute,
  ApiMarketDexscreenerSearchRoute: ApiMarketDexscreenerSearchRoute,
  ApiMarketGeckoterminalNetworksRoute: ApiMarketGeckoterminalNetworksRoute,
  ApiMarketGmgnHotSearchesRoute: ApiMarketGmgnHotSearchesRoute,
  ApiMarketGmgnTrendingRoute: ApiMarketGmgnTrendingRoute,
  ApiMarketCoingeckoChartIdRoute: ApiMarketCoingeckoChartIdRoute,
  ApiMarketCoingeckoCoinIdRoute: ApiMarketCoingeckoCoinIdRoute,
  ApiMarketDexscreenerTrendingChainIdRoute:
    ApiMarketDexscreenerTrendingChainIdRoute,
  ApiMarketGeckoterminalPoolsNetworkIdRoute:
    ApiMarketGeckoterminalPoolsNetworkIdRoute,
  ApiMarketGeckoterminalTrendingNetworkIdRoute:
    ApiMarketGeckoterminalTrendingNetworkIdRoute,
  ApiMarketDexscreenerTokenChainIdAddressRoute:
    ApiMarketDexscreenerTokenChainIdAddressRoute,
  ApiMarketGeckoterminalOhlcvNetworkIdPoolAddressRoute:
    ApiMarketGeckoterminalOhlcvNetworkIdPoolAddressRoute,
  ApiMarketGeckoterminalTokenNetworkIdAddressRoute:
    ApiMarketGeckoterminalTokenNetworkIdAddressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
