/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAgentsRouteImport } from './routes/app/agents'
import { Route as AppAgentsHubRouteImport } from './routes/app/agents-hub'
import { Route as AppAiFeedRouteImport } from './routes/app/ai-feed'
import { Route as AppDataRouteImport } from './routes/app/data'
import { Route as AppDisclaimerRouteImport } from './routes/app/disclaimer'
import { Route as AppLeaderboardRouteImport } from './routes/app/leaderboard'
import { Route as AppMarketsRouteImport } from './routes/app/markets'
import { Route as AppMethodologyRouteImport } from './routes/app/methodology'
import { Route as AppPortfolioRouteImport } from './routes/app/portfolio'
import { Route as AppSwapRouteImport } from './routes/app/swap'
import { Route as AppTokenRouteImport } from './routes/app/token'
import { Route as AppTrendingRouteImport } from './routes/app/trending'
import { Route as AppWatchlistRouteImport } from './routes/app/watchlist'
import { Route as AppXstocksRouteImport } from './routes/app/xstocks'
import { Route as ApiAnalyticsBridgeEventRouteImport } from './routes/api/analytics/bridge-event'
import { Route as ApiAnalyticsSwapEventRouteImport } from './routes/api/analytics/swap-event'
import { Route as ApiBridgeChainsRouteImport } from './routes/api/bridge/chains'
import { Route as ApiBridgeProvidersRouteImport } from './routes/api/bridge/providers'
import { Route as ApiBridgeQuoteRouteImport } from './routes/api/bridge/quote'
import { Route as ApiBridgeStatusRouteImport } from './routes/api/bridge/status'
import { Route as ApiBridgeTokensRouteImport } from './routes/api/bridge/tokens'
import { Route as ApiFeedNewLaunchesRouteImport } from './routes/api/feed/new-launches'
import { Route as ApiFeedSnapshotRouteImport } from './routes/api/feed/snapshot'
import { Route as ApiMarketStatusRouteImport } from './routes/api/market/status'
import { Route as ApiPortfolioHoldingsRouteImport } from './routes/api/portfolio/holdings'
import { Route as ApiSwapPriceRouteImport } from './routes/api/swap/price'
import { Route as ApiSwapQuoteRouteImport } from './routes/api/swap/quote'
import { Route as ApiSwapResolveTokenRouteImport } from './routes/api/swap/resolve-token'
import { Route as ApiSwapTokensRouteImport } from './routes/api/swap/tokens'
import { Route as AppAgentsHubIndexRouteImport } from './routes/app/agents-hub.index'
import { Route as AppAgentsHubSlugRouteImport } from './routes/app/agents-hub.$slug'
import { Route as AppAgentsSlugRouteImport } from './routes/app/agents.$slug'
import { Route as AppCoinCoinIdRouteImport } from './routes/app/coin.$coinId'
import { Route as AppMarketsIndexRouteImport } from './routes/app/markets.index'
import { Route as AppMarketsGlobalRouteImport } from './routes/app/markets.global'
import { Route as AppMarketsHotSearchesRouteImport } from './routes/app/markets.hot-searches'
import { Route as AppMarketsTrendingRouteImport } from './routes/app/markets.trending'
import { Route as AppSwapIndexRouteImport } from './routes/app/swap.index'
import { Route as AppTokenIndexRouteImport } from './routes/app/token.index'
import { Route as ApiMarketCoingeckoCoinsRouteImport } from './routes/api/market/coingecko/coins'
import { Route as ApiMarketCoingeckoSearchRouteImport } from './routes/api/market/coingecko/search'
import { Route as ApiMarketCoingeckoTrendingRouteImport } from './routes/api/market/coingecko/trending'
import { Route as ApiMarketDexscreenerPairsRouteImport } from './routes/api/market/dexscreener/pairs'
import { Route as ApiMarketDexscreenerSearchRouteImport } from './routes/api/market/dexscreener/search'
import { Route as ApiMarketGeckoterminalNetworksRouteImport } from './routes/api/market/geckoterminal/networks'
import { Route as ApiMarketGmgnHotSearchesRouteImport } from './routes/api/market/gmgn/hot-searches'
import { Route as ApiMarketGmgnTrendingRouteImport } from './routes/api/market/gmgn/trending'
import { Route as AppMarketsRobinhoodTokenAddressRouteImport } from './routes/app/markets.robinhood.$tokenAddress'
import { Route as AppTokenChainIdAddressRouteImport } from './routes/app/token.$chainId.$address'
import { Route as ApiFeedManualLookupChainIdAddressRouteImport } from './routes/api/feed/manual-lookup.$chainId.$address'
import { Route as ApiMarketCoingeckoChartIdRouteImport } from './routes/api/market/coingecko/chart.$id'
import { Route as ApiMarketCoingeckoCoinIdRouteImport } from './routes/api/market/coingecko/coin.$id'
import { Route as ApiMarketDexscreenerTrendingChainIdRouteImport } from './routes/api/market/dexscreener/trending.$chainId'
import { Route as ApiMarketGeckoterminalPoolsNetworkIdRouteImport } from './routes/api/market/geckoterminal/pools.$networkId'
import { Route as ApiMarketGeckoterminalTrendingNetworkIdRouteImport } from './routes/api/market/geckoterminal/trending.$networkId'
import { Route as ApiMarketDexscreenerTokenChainIdAddressRouteImport } from './routes/api/market/dexscreener/token.$chainId.$address'
import { Route as ApiMarketGeckoterminalOhlcvNetworkIdPoolAddressRouteImport } from './routes/api/market/geckoterminal/ohlcv.$networkId.$poolAddress'
import { Route as ApiMarketGeckoterminalTokenNetworkIdAddressRouteImport } from './routes/api/market/geckoterminal/token.$networkId.$address'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsHubRoute = AppAgentsHubRouteImport.update({
  id: '/agents-hub',
  path: '/agents-hub',
  getParentRoute: () => AppRoute,
} as any)
const AppAiFeedRoute = AppAiFeedRouteImport.update({
  id: '/ai-feed',
  path: '/ai-feed',
  getParentRoute: () => AppRoute,
} as any)
const AppDataRoute = AppDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AppRoute,
} as any)
const AppDisclaimerRoute = AppDisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketsRoute = AppMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AppRoute,
} as any)
const AppMethodologyRoute = AppMethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppSwapRoute = AppSwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => AppRoute,
} as any)
const AppTokenRoute = AppTokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => AppRoute,
} as any)
const AppTrendingRoute = AppTrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => AppRoute,
} as any)
const AppWatchlistRoute = AppWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AppRoute,
} as any)
const AppXstocksRoute = AppXstocksRouteImport.update({
  id: '/xstocks',
  path: '/xstocks',
  getParentRoute: () => AppRoute,
} as any)
const ApiAnalyticsBridgeEventRoute = ApiAnalyticsBridgeEventRouteImport.update({
  id: '/api/analytics/bridge-event',
  path: '/api/analytics/bridge-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsSwapEventRoute = ApiAnalyticsSwapEventRouteImport.update({
  id: '/api/analytics/swap-event',
  path: '/api/analytics/swap-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBridgeChainsRoute = ApiBridgeChainsRouteImport.update({
  id: '/api/bridge/chains',
  path: '/api/bridge/chains',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBridgeProvidersRoute = ApiBridgeProvidersRouteImport.update({
  id: '/api/bridge/providers',
  path: '/api/bridge/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBridgeQuoteRoute = ApiBridgeQuoteRouteImport.update({
  id: '/api/bridge/quote',
  path: '/api/bridge/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBridgeStatusRoute = ApiBridgeStatusRouteImport.update({
  id: '/api/bridge/status',
  path: '/api/bridge/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBridgeTokensRoute = ApiBridgeTokensRouteImport.update({
  id: '/api/bridge/tokens',
  path: '/api/bridge/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedNewLaunchesRoute = ApiFeedNewLaunchesRouteImport.update({
  id: '/api/feed/new-launches',
  path: '/api/feed/new-launches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedSnapshotRoute = ApiFeedSnapshotRouteImport.update({
  id: '/api/feed/snapshot',
  path: '/api/feed/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketStatusRoute = ApiMarketStatusRouteImport.update({
  id: '/api/market/status',
  path: '/api/market/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortfolioHoldingsRoute = ApiPortfolioHoldingsRouteImport.update({
  id: '/api/portfolio/holdings',
  path: '/api/portfolio/holdings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwapPriceRoute = ApiSwapPriceRouteImport.update({
  id: '/api/swap/price',
  path: '/api/swap/price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwapQuoteRoute = ApiSwapQuoteRouteImport.update({
  id: '/api/swap/quote',
  path: '/api/swap/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwapResolveTokenRoute = ApiSwapResolveTokenRouteImport.update({
  id: '/api/swap/resolve-token',
  path: '/api/swap/resolve-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwapTokensRoute = ApiSwapTokensRouteImport.update({
  id: '/api/swap/tokens',
  path: '/api/swap/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentsHubIndexRoute = AppAgentsHubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAgentsHubRoute,
} as any)
const AppAgentsHubSlugRoute = AppAgentsHubSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppAgentsHubRoute,
} as any)
const AppAgentsSlugRoute = AppAgentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppAgentsRoute,
} as any)
const AppCoinCoinIdRoute = AppCoinCoinIdRouteImport.update({
  id: '/coin/$coinId',
  path: '/coin/$coinId',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketsIndexRoute = AppMarketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMarketsRoute,
} as any)
const AppMarketsGlobalRoute = AppMarketsGlobalRouteImport.update({
  id: '/global',
  path: '/global',
  getParentRoute: () => AppMarketsRoute,
} as any)
const AppMarketsHotSearchesRoute = AppMarketsHotSearchesRouteImport.update({
  id: '/hot-searches',
  path: '/hot-searches',
  getParentRoute: () => AppMarketsRoute,
} as any)
const AppMarketsTrendingRoute = AppMarketsTrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => AppMarketsRoute,
} as any)
const AppSwapIndexRoute = AppSwapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSwapRoute,
} as any)
const AppTokenIndexRoute = AppTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTokenRoute,
} as any)
const ApiMarketCoingeckoCoinsRoute = ApiMarketCoingeckoCoinsRouteImport.update({
  id: '/api/market/coingecko/coins',
  path: '/api/market/coingecko/coins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketCoingeckoSearchRoute =
  ApiMarketCoingeckoSearchRouteImport.update({
    id: '/api/market/coingecko/search',
    path: '/api/market/coingecko/search',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketCoingeckoTrendingRoute =
  ApiMarketCoingeckoTrendingRouteImport.update({
    id: '/api/market/coingecko/trending',
    path: '/api/market/coingecko/trending',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketDexscreenerPairsRoute =
  ApiMarketDexscreenerPairsRouteImport.update({
    id: '/api/market/dexscreener/pairs',
    path: '/api/market/dexscreener/pairs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketDexscreenerSearchRoute =
  ApiMarketDexscreenerSearchRouteImport.update({
    id: '/api/market/dexscreener/search',
    path: '/api/market/dexscreener/search',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketGeckoterminalNetworksRoute =
  ApiMarketGeckoterminalNetworksRouteImport.update({
    id: '/api/market/geckoterminal/networks',
    path: '/api/market/geckoterminal/networks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketGmgnHotSearchesRoute =
  ApiMarketGmgnHotSearchesRouteImport.update({
    id: '/api/market/gmgn/hot-searches',
    path: '/api/market/gmgn/hot-searches',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketGmgnTrendingRoute = ApiMarketGmgnTrendingRouteImport.update({
  id: '/api/market/gmgn/trending',
  path: '/api/market/gmgn/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMarketsRobinhoodTokenAddressRoute =
  AppMarketsRobinhoodTokenAddressRouteImport.update({
    id: '/robinhood/$tokenAddress',
    path: '/robinhood/$tokenAddress',
    getParentRoute: () => AppMarketsRoute,
  } as any)
const AppTokenChainIdAddressRoute = AppTokenChainIdAddressRouteImport.update({
  id: '/$chainId/$address',
  path: '/$chainId/$address',
  getParentRoute: () => AppTokenRoute,
} as any)
const ApiFeedManualLookupChainIdAddressRoute =
  ApiFeedManualLookupChainIdAddressRouteImport.update({
    id: '/api/feed/manual-lookup/$chainId/$address',
    path: '/api/feed/manual-lookup/$chainId/$address',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketCoingeckoChartIdRoute =
  ApiMarketCoingeckoChartIdRouteImport.update({
    id: '/api/market/coingecko/chart/$id',
    path: '/api/market/coingecko/chart/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketCoingeckoCoinIdRoute =
  ApiMarketCoingeckoCoinIdRouteImport.update({
    id: '/api/market/coingecko/coin/$id',
    path: '/api/market/coingecko/coin/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketDexscreenerTrendingChainIdRoute =
  ApiMarketDexscreenerTrendingChainIdRouteImport.update({
    id: '/api/market/dexscreener/trending/$chainId',
    path: '/api/market/dexscreener/trending/$chainId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketGeckoterminalPoolsNetworkIdRoute =
  ApiMarketGeckoterminalPoolsNetworkIdRouteImport.update({
    id: '/api/market/geckoterminal/pools/$networkId',
    path: '/api/market/geckoterminal/pools/$networkId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketGeckoterminalTrendingNetworkIdRoute =
  ApiMarketGeckoterminalTrendingNetworkIdRouteImport.update({
    id: '/api/market/geckoterminal/trending/$networkId',
    path: '/api/market/geckoterminal/trending/$networkId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketDexscreenerTokenChainIdAddressRoute =
  ApiMarketDexscreenerTokenChainIdAddressRouteImport.update({
    id: '/api/market/dexscreener/token/$chainId/$address',
    path: '/api/market/dexscreener/token/$chainId/$address',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketGeckoterminalOhlcvNetworkIdPoolAddressRoute =
  ApiMarketGeckoterminalOhlcvNetworkIdPoolAddressRouteImport.update({
    id: '/api/market/geckoterminal/ohlcv/$networkId/$poolAddress',
    path: '/api/market/geckoterminal/ohlcv/$networkId/$poolAddress',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketGeckoterminalTokenNetworkIdAddressRoute =
  ApiMarketGeckoterminalTokenNetworkIdAddressRouteImport.update({
    id: '/api/market/geckoterminal/token/$networkId/$address',
    path: '/api/market/geckoterminal/token/$networkId/$address',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/agents': typeof AppAgentsRouteWithChildren
  '/app/agents-hub': typeof AppAgentsHubRouteWithChildren
  '/app/ai-feed': typeof AppAiFeedRoute
  '/app/data': typeof AppDataRoute
  '/app/disclaimer': typeof AppDisclaimerRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/markets': typeof AppMarketsRouteWithChildren
  '/app/methodology': typeof AppMethodologyRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/swap': typeof AppSwapRouteWithChildren
  '/app/token': typeof AppTokenRouteWithChildren
  '/app/trending': typeof AppTrendingRoute
  '/app/watchlist': typeof AppWatchlistRoute
  '/app/xstocks': typeof AppXstocksRoute
  '/app/': typeof AppIndexRoute
  '/api/analytics/bridge-event': typeof ApiAnalyticsBridgeEventRoute
  '/api/analytics/swap-event': typeof ApiAnalyticsSwapEventRoute
  '/api/bridge/chains': typeof ApiBridgeChainsRoute
  '/api/bridge/providers': typeof ApiBridgeProvidersRoute
  '/api/bridge/quote': typeof ApiBridgeQuoteRoute
  '/api/bridge/status': typeof ApiBridgeStatusRoute
  '/api/bridge/tokens': typeof ApiBridgeTokensRoute
  '/api/feed/new-launches': typeof ApiFeedNewLaunchesRoute
  '/api/feed/snapshot': typeof ApiFeedSnapshotRoute
  '/api/market/status': typeof ApiMarketStatusRoute
  '/api/portfolio/holdings': typeof ApiPortfolioHoldingsRoute
  '/api/swap/price': typeof ApiSwapPriceRoute
  '/api/swap/quote': typeof ApiSwapQuoteRoute
  '/api/swap/resolve-token': typeof ApiSwapResolveTokenRoute
  '/api/swap/tokens': typeof ApiSwapTokensRoute
  '/app/agents-hub/$slug': typeof AppAgentsHubSlugRoute
  '/app/agents/$slug': typeof AppAgentsSlugRoute
  '/app/coin/$coinId': typeof AppCoinCoinIdRoute
  '/app/markets/global': typeof AppMarketsGlobalRoute
  '/app/markets/hot-searches': typeof AppMarketsHotSearchesRoute
  '/app/markets/trending': typeof AppMarketsTrendingRoute
  '/app/agents-hub/': typeof AppAgentsHubIndexRoute
  '/app/markets/': typeof AppMarketsIndexRoute
  '/app/swap/': typeof AppSwapIndexRoute
  '/app/token/': typeof AppTokenIndexRoute
  '/api/market/coingecko/coins': typeof ApiMarketCoingeckoCoinsRoute
  '/api/market/coingecko/search': typeof ApiMarketCoingeckoSearchRoute
  '/api/market/coingecko/trending': typeof ApiMarketCoingeckoTrendingRoute
  '/api/market/dexscreener/pairs': typeof ApiMarketDexscreenerPairsRoute
  '/api/market/dexscreener/search': typeof ApiMarketDexscreenerSearchRoute
  '/api/market/geckoterminal/networks': typeof ApiMarketGeckoterminalNetworksRoute
  '/api/market/gmgn/hot-searches': typeof ApiMarketGmgnHotSearchesRoute
  '/api/market/gmgn/trending': typeof ApiMarketGmgnTrendingRoute
  '/app/markets/robinhood/$tokenAddress': typeof AppMarketsRobinhoodTokenAddressRoute
  '/app/token/$chainId/$address': typeof AppTokenChainIdAddressRoute
  '/api/feed/manual-lookup/$chainId/$address': typeof ApiFeedManualLookupChainIdAddressRoute
  '/api/market/coingecko/chart/$id': typeof ApiMarketCoingeckoChartIdRoute
  '/api/market/coingecko/coin/$id': typeof ApiMarketCoingeckoCoinIdRoute
  '/api/market/dexscreener/trending/$chainId': typeof ApiMarketDexscreenerTrendingChainIdRoute
  '/api/market/geckoterminal/pools/$networkId': typeof ApiMarketGeckoterminalPoolsNetworkIdRoute
  '/api/market/geckoterminal/trending/$networkId': typeof ApiMarketGeckoterminalTrendingNetworkIdRoute
  '/api/market/dexscreener/token/$chainId/$address': typeof ApiMarketDexscreenerTokenChainIdAddressRoute
  '/api/market/geckoterminal/ohlcv/$networkId/$poolAddress': typeof ApiMarketGeckoterminalOhlcvNetworkIdPoolAddressRoute
  '/api/market/geckoterminal/token/$networkId/$address': typeof ApiMarketGeckoterminalTokenNetworkIdAddressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/agents': typeof AppAgentsRouteWithChildren
  '/app/ai-feed': typeof AppAiFeedRoute
  '/app/data': typeof AppDataRoute
  '/app/disclaimer': typeof AppDisclaimerRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/methodology': typeof AppMethodologyRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/trending': typeof AppTrendingRoute
  '/app/watchlist': typeof AppWatchlistRoute
  '/app/xstocks': typeof AppXstocksRoute
  '/app': typeof AppIndexRoute
  '/api/analytics/bridge-event': typeof ApiAnalyticsBridgeEventRoute
  '/api/analytics/swap-event': typeof ApiAnalyticsSwapEventRoute
  '/api/bridge/chains': typeof ApiBridgeChainsRoute
  '/api/bridge/providers': typeof ApiBridgeProvidersRoute
  '/api/bridge/quote': typeof ApiBridgeQuoteRoute
  '/api/bridge/status': typeof ApiBridgeStatusRoute
  '/api/bridge/tokens': typeof ApiBridgeTokensRoute
  '/api/feed/new-launches': typeof ApiFeedNewLaunchesRoute
  '/api/feed/snapshot': typeof ApiFeedSnapshotRoute
  '/api/market/status': typeof ApiMarketStatusRoute
  '/api/portfolio/holdings': typeof ApiPortfolioHoldingsRoute
  '/api/swap/price': typeof ApiSwapPriceRoute
  '/api/swap/quote': typeof ApiSwapQuoteRoute
  '/api/swap/resolve-token': typeof ApiSwapResolveTokenRoute
  '/api/swap/tokens': typeof ApiSwapTokensRoute
  '/app/agents-hub/$slug': typeof AppAgentsHubSlugRoute
  '/app/agents/$slug': typeof AppAgentsSlugRoute
  '/app/coin/$coinId': typeof AppCoinCoinIdRoute
  '/app/markets/global': typeof AppMarketsGlobalRoute
  '/app/markets/hot-searches': typeof AppMarketsHotSearchesRoute
  '/app/markets/trending': typeof AppMarketsTrendingRoute
  '/app/agents-hub': typeof AppAgentsHubIndexRoute
  '/app/markets': typeof AppMarketsIndexRoute
  '/app/swap': typeof AppSwapIndexRoute
  '/app/token': typeof AppTokenIndexRoute
  '/api/market/coingecko/coins': typeof ApiMarketCoingeckoCoinsRoute
  '/api/market/coingecko/search': typeof ApiMarketCoingeckoSearchRoute
  '/api/market/coingecko/trending': typeof ApiMarketCoingeckoTrendingRoute
  '/api/market/dexscreener/pairs': typeof ApiMarketDexscreenerPairsRoute
  '/api/market/dexscreener/search': typeof ApiMarketDexscreenerSearchRoute
  '/api/market/geckoterminal/networks': typeof ApiMarketGeckoterminalNetworksRoute
  '/api/market/gmgn/hot-searches': typeof ApiMarketGmgnHotSearchesRoute
  '/api/market/gmgn/trending': typeof ApiMarketGmgnTrendingRoute
  '/app/markets/robinhood/$tokenAddress': typeof AppMarketsRobinhoodTokenAddressRoute
  '/app/token/$chainId/$address': typeof AppTokenChainIdAddressRoute
  '/api/feed/manual-lookup/$chainId/$address': typeof ApiFeedManualLookupChainIdAddressRoute
  '/api/market/coingecko/chart/$id': typeof ApiMarketCoingeckoChartIdRoute
  '/api/market/coingecko/coin/$id': typeof ApiMarketCoingeckoCoinIdRoute
  '/api/market/dexscreener/trending/$chainId': typeof ApiMarketDexscreenerTrendingChainIdRoute
  '/api/market/geckoterminal/pools/$networkId': typeof ApiMarketGeckoterminalPoolsNetworkIdRoute
  '/api/market/geckoterminal/trending/$networkId': typeof ApiMarketGeckoterminalTrendingNetworkIdRoute
  '/api/market/dexscreener/token/$chainId/$address': typeof ApiMarketDexscreenerTokenChainIdAddressRoute
  '/api/market/geckoterminal/ohlcv/$networkId/$poolAddress': typeof ApiMarketGeckoterminalOhlcvNetworkIdPoolAddressRoute
  '/api/market/geckoterminal/token/$networkId/$address': typeof ApiMarketGeckoterminalTokenNetworkIdAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/agents': typeof AppAgentsRouteWithChildren
  '/app/agents-hub': typeof AppAgentsHubRouteWithChildren
  '/app/ai-feed': typeof AppAiFeedRoute
  '/app/data': typeof AppDataRoute
  '/app/disclaimer': typeof AppDisclaimerRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/markets': typeof AppMarketsRouteWithChildren
  '/app/methodology': typeof AppMethodologyRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/swap': typeof AppSwapRouteWithChildren
  '/app/token': typeof AppTokenRouteWithChildren
  '/app/trending': typeof AppTrendingRoute
  '/app/watchlist': typeof AppWatchlistRoute
  '/app/xstocks': typeof AppXstocksRoute
  '/app/': typeof AppIndexRoute
  '/api/analytics/bridge-event': typeof ApiAnalyticsBridgeEventRoute
  '/api/analytics/swap-event': typeof ApiAnalyticsSwapEventRoute
  '/api/bridge/chains': typeof ApiBridgeChainsRoute
  '/api/bridge/providers': typeof ApiBridgeProvidersRoute
  '/api/bridge/quote': typeof ApiBridgeQuoteRoute
  '/api/bridge/status': typeof ApiBridgeStatusRoute
  '/api/bridge/tokens': typeof ApiBridgeTokensRoute
  '/api/feed/new-launches': typeof ApiFeedNewLaunchesRoute
  '/api/feed/snapshot': typeof ApiFeedSnapshotRoute
  '/api/market/status': typeof ApiMarketStatusRoute
  '/api/portfolio/holdings': typeof ApiPortfolioHoldingsRoute
  '/api/swap/price': typeof ApiSwapPriceRoute
  '/api/swap/quote': typeof ApiSwapQuoteRoute
  '/api/swap/resolve-token': typeof ApiSwapResolveTokenRoute
  '/api/swap/tokens': typeof ApiSwapTokensRoute
  '/app/agents-hub/$slug': typeof AppAgentsHubSlugRoute
  '/app/agents/$slug': typeof AppAgentsSlugRoute
  '/app/coin/$coinId': typeof AppCoinCoinIdRoute
  '/app/markets/global': typeof AppMarketsGlobalRoute
  '/app/markets/hot-searches': typeof AppMarketsHotSearchesRoute
  '/app/markets/trending': typeof AppMarketsTrendingRoute
  '/app/agents-hub/': typeof AppAgentsHubIndexRoute
  '/app/markets/': typeof AppMarketsIndexRoute
  '/app/swap/': typeof AppSwapIndexRoute
  '/app/token/': typeof AppTokenIndexRoute
  '/api/market/coingecko/coins': typeof ApiMarketCoingeckoCoinsRoute
  '/api/market/coingecko/search': typeof ApiMarketCoingeckoSearchRoute
  '/api/market/coingecko/trending': typeof ApiMarketCoingeckoTrendingRoute
  '/api/market/dexscreener/pairs': typeof ApiMarketDexscreenerPairsRoute
  '/api/market/dexscreener/search': typeof ApiMarketDexscreenerSearchRoute
  '/api/market/geckoterminal/networks': typeof ApiMarketGeckoterminalNetworksRoute
  '/api/market/gmgn/hot-searches': typeof ApiMarketGmgnHotSearchesRoute
  '/api/market/gmgn/trending': typeof ApiMarketGmgnTrendingRoute
  '/app/markets/robinhood/$tokenAddress': typeof AppMarketsRobinhoodTokenAddressRoute
  '/app/token/$chainId/$address': typeof AppTokenChainIdAddressRoute
  '/api/feed/manual-lookup/$chainId/$address': typeof ApiFeedManualLookupChainIdAddressRoute
  '/api/market/coingecko/chart/$id': typeof ApiMarketCoingeckoChartIdRoute
  '/api/market/coingecko/coin/$id': typeof ApiMarketCoingeckoCoinIdRoute
  '/api/market/dexscreener/trending/$chainId': typeof ApiMarketDexscreenerTrendingChainIdRoute
  '/api/market/geckoterminal/pools/$networkId': typeof ApiMarketGeckoterminalPoolsNetworkIdRoute
  '/api/market/geckoterminal/trending/$networkId': typeof ApiMarketGeckoterminalTrendingNetworkIdRoute
  '/api/market/dexscreener/token/$chainId/$address': typeof ApiMarketDexscreenerTokenChainIdAddressRoute
  '/api/market/geckoterminal/ohlcv/$networkId/$poolAddress': typeof ApiMarketGeckoterminalOhlcvNetworkIdPoolAddressRoute
  '/api/market/geckoterminal/token/$networkId/$address': typeof ApiMarketGeckoterminalTokenNetworkIdAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/privacy'
    | '/terms'
    | '/app/agents'
    | '/app/agents-hub'
    | '/app/ai-feed'
    | '/app/data'
    | '/app/disclaimer'
    | '/app/leaderboard'
    | '/app/markets'
    | '/app/methodology'
    | '/app/portfolio'
    | '/app/swap'
    | '/app/token'
    | '/app/trending'
    | '/app/watchlist'
    | '/app/xstocks'
    | '/app/'
    | '/api/analytics/bridge-event'
    | '/api/analytics/swap-event'
    | '/api/bridge/chains'
    | '/api/bridge/providers'
    | '/api/bridge/quote'
    | '/api/bridge/status'
    | '/api/bridge/tokens'
    | '/api/feed/new-launches'
    | '/api/feed/snapshot'
    | '/api/market/status'
    | '/api/portfolio/holdings'
    | '/api/swap/price'
    | '/api/swap/quote'
    | '/api/swap/resolve-token'
    | '/api/swap/tokens'
    | '/app/agents-hub/$slug'
    | '/app/agents/$slug'
    | '/app/coin/$coinId'
    | '/app/markets/global'
    | '/app/markets/hot-searches'
    | '/app/markets/trending'
    | '/app/agents-hub/'
    | '/app/markets/'
    | '/app/swap/'
    | '/app/token/'
    | '/api/market/coingecko/coins'
    | '/api/market/coingecko/search'
    | '/api/market/coingecko/trending'
    | '/api/market/dexscreener/pairs'
    | '/api/market/dexscreener/search'
    | '/api/market/geckoterminal/networks'
    | '/api/market/gmgn/hot-searches'
    | '/api/market/gmgn/trending'
    | '/app/markets/robinhood/$tokenAddress'
    | '/app/token/$chainId/$address'
    | '/api/feed/manual-lookup/$chainId/$address'
    | '/api/market/coingecko/chart/$id'
    | '/api/market/coingecko/coin/$id'
    | '/api/market/dexscreener/trending/$chainId'
    | '/api/market/geckoterminal/pools/$networkId'
    | '/api/market/geckoterminal/trending/$networkId'
    | '/api/market/dexscreener/token/$chainId/$address'
    | '/api/market/geckoterminal/ohlcv/$networkId/$poolAddress'
    | '/api/market/geckoterminal/token/$networkId/$address'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/app/agents'
    | '/app/ai-feed'
    | '/app/data'
    | '/app/disclaimer'
    | '/app/leaderboard'
    | '/app/methodology'
    | '/app/portfolio'
    | '/app/trending'
    | '/app/watchlist'
    | '/app/xstocks'
    | '/app'
    | '/api/analytics/bridge-event'
    | '/api/analytics/swap-event'
    | '/api/bridge/chains'
    | '/api/bridge/providers'
    | '/api/bridge/quote'
    | '/api/bridge/status'
    | '/api/bridge/tokens'
    | '/api/feed/new-launches'
    | '/api/feed/snapshot'
    | '/api/market/status'
    | '/api/portfolio/holdings'
    | '/api/swap/price'
    | '/api/swap/quote'
    | '/api/swap/resolve-token'
    | '/api/swap/tokens'
    | '/app/agents-hub/$slug'
    | '/app/agents/$slug'
    | '/app/coin/$coinId'
    | '/app/markets/global'
    | '/app/markets/hot-searches'
    | '/app/markets/trending'
    | '/app/agents-hub'
    | '/app/markets'
    | '/app/swap'
    | '/app/token'
    | '/api/market/coingecko/coins'
    | '/api/market/coingecko/search'
    | '/api/market/coingecko/trending'
    | '/api/market/dexscreener/pairs'
    | '/api/market/dexscreener/search'
    | '/api/market/geckoterminal/networks'
    | '/api/market/gmgn/hot-searches'
    | '/api/market/gmgn/trending'
    | '/app/markets/robinhood/$tokenAddress'
    | '/app/token/$chainId/$address'
    | '/api/feed/manual-lookup/$chainId/$address'
    | '/api/market/coingecko/chart/$id'
    | '/api/market/coingecko/coin/$id'
    | '/api/market/dexscreener/trending/$chainId'
    | '/api/market/geckoterminal/pools/$networkId'
    | '/api/market/geckoterminal/trending/$networkId'
    | '/api/market/dexscreener/token/$chainId/$address'
    | '/api/market/geckoterminal/ohlcv/$networkId/$poolAddress'
    | '/api/market/geckoterminal/token/$networkId/$address'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/privacy'
    | '/terms'
    | '/app/agents'
    | '/app/agents-hub'
    | '/app/ai-feed'
    | '/app/data'
    | '/app/disclaimer'
    | '/app/leaderboard'
    | '/app/markets'
    | '/app/methodology'
    | '/app/portfolio'
    | '/app/swap'
    | '/app/token'
    | '/app/trending'
    | '/app/watchlist'
    | '/app/xstocks'
    | '/app/'
    | '/api/analytics/bridge-event'
    | '/api/analytics/swap-event'
    | '/api/bridge/chains'
    | '/api/bridge/providers'
    | '/api/bridge/quote'
    | '/api/bridge/status'
    | '/api/bridge/tokens'
    | '/api/feed/new-launches'
    | '/api/feed/snapshot'
    | '/api/market/status'
    | '/api/portfolio/holdings'
    | '/api/swap/price'
    | '/api/swap/quote'
    | '/api/swap/resolve-token'
    | '/api/swap/tokens'
    | '/app/agents-hub/$slug'
    | '/app/agents/$slug'
    | '/app/coin/$coinId'
    | '/app/markets/global'
    | '/app/markets/hot-searches'
    | '/app/markets/trending'
    | '/app/agents-hub/'
    | '/app/markets/'
    | '/app/swap/'
    | '/app/token/'
    | '/api/market/coingecko/coins'
    | '/api/market/coingecko/search'
    | '/api/market/coingecko/trending'
    | '/api/market/dexscreener/pairs'
    | '/api/market/dexscreener/search'
    | '/api/market/geckoterminal/networks'
    | '/api/market/gmgn/hot-searches'
    | '/api/market/gmgn/trending'
    | '/app/markets/robinhood/$tokenAddress'
    | '/app/token/$chainId/$address'
    | '/api/feed/manual-lookup/$chainId/$address'
    | '/api/market/coingecko/chart/$id'
    | '/api/market/coingecko/coin/$id'
    | '/api/market/dexscreener/trending/$chainId'
    | '/api/market/geckoterminal/pools/$networkId'
    | '/api/market/geckoterminal/trending/$networkId'
    | '/api/market/dexscreener/token/$chainId/$address'
    | '/api/market/geckoterminal/ohlcv/$networkId/$poolAddress'
    | '/api/market/geckoterminal/token/$networkId/$address'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiAnalyticsBridgeEventRoute: typeof ApiAnalyticsBridgeEventRoute
  ApiAnalyticsSwapEventRoute: typeof ApiAnalyticsSwapEventRoute
  ApiBridgeChainsRoute: typeof ApiBridgeChainsRoute
  ApiBridgeProvidersRoute: typeof ApiBridgeProvidersRoute
  ApiBridgeQuoteRoute: typeof ApiBridgeQuoteRoute
  ApiBridgeStatusRoute: typeof ApiBridgeStatusRoute
  ApiBridgeTokensRoute: typeof ApiBridgeTokensRoute
  ApiFeedNewLaunchesRoute: typeof ApiFeedNewLaunchesRoute
  ApiFeedSnapshotRoute: typeof ApiFeedSnapshotRoute
  ApiMarketStatusRoute: typeof ApiMarketStatusRoute
  ApiPortfolioHoldingsRoute: typeof ApiPortfolioHoldingsRoute
  ApiSwapPriceRoute: typeof ApiSwapPriceRoute
  ApiSwapQuoteRoute: typeof ApiSwapQuoteRoute
  ApiSwapResolveTokenRoute: typeof ApiSwapResolveTokenRoute
  ApiSwapTokensRoute: typeof ApiSwapTokensRoute
  ApiMarketCoingeckoCoinsRoute: typeof ApiMarketCoingeckoCoinsRoute
  ApiMarketCoingeckoSearchRoute: typeof ApiMarketCoingeckoSearchRoute
  ApiMarketCoingeckoTrendingRoute: typeof ApiMarketCoingeckoTrendingRoute
  ApiMarketDexscreenerPairsRoute: typeof ApiMarketDexscreenerPairsRoute
  ApiMarketDexscreenerSearchRoute: typeof ApiMarketDexscreenerSearchRoute
  ApiMarketGeckoterminalNetworksRoute: typeof ApiMarketGeckoterminalNetworksRoute
  ApiMarketGmgnHotSearchesRoute: typeof ApiMarketGmgnHotSearchesRoute
  ApiMarketGmgnTrendingRoute: typeof ApiMarketGmgnTrendingRoute
  ApiFeedManualLookupChainIdAddressRoute: typeof ApiFeedManualLookupChainIdAddressRoute
  ApiMarketCoingeckoChartIdRoute: typeof ApiMarketCoingeckoChartIdRoute
  ApiMarketCoingeckoCoinIdRoute: typeof ApiMarketCoingeckoCoinIdRoute
  ApiMarketDexscreenerTrendingChainIdRoute: typeof ApiMarketDexscreenerTrendingChainIdRoute
  ApiMarketGeckoterminalPoolsNetworkIdRoute: typeof ApiMarketGeckoterminalPoolsNetworkIdRoute
  ApiMarketGeckoterminalTrendingNetworkIdRoute: typeof ApiMarketGeckoterminalTrendingNetworkIdRoute
  ApiMarketDexscreenerTokenChainIdAddressRoute: typeof ApiMarketDexscreenerTokenChainIdAddressRoute
  ApiMarketGeckoterminalOhlcvNetworkIdPoolAddressRoute: typeof ApiMarketGeckoterminalOhlcvNetworkIdPoolAddressRoute
  ApiMarketGeckoterminalTokenNetworkIdAddressRoute: typeof ApiMarketGeckoterminalTokenNetworkIdAddressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents-hub': {
      id: '/app/agents-hub'
      path: '/agents-hub'
      fullPath: '/app/agents-hub'
      preLoaderRoute: typeof AppAgentsHubRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-feed': {
      id: '/app/ai-feed'
      path: '/ai-feed'
      fullPath: '/app/ai-feed'
      preLoaderRoute: typeof AppAiFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/data': {
      id: '/app/data'
      path: '/data'
      fullPath: '/app/data'
      preLoaderRoute: typeof AppDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/disclaimer': {
      id: '/app/disclaimer'
      path: '/disclaimer'
      fullPath: '/app/disclaimer'
      preLoaderRoute: typeof AppDisclaimerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboard': {
      id: '/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/markets': {
      id: '/app/markets'
      path: '/markets'
      fullPath: '/app/markets'
      preLoaderRoute: typeof AppMarketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/methodology': {
      id: '/app/methodology'
      path: '/methodology'
      fullPath: '/app/methodology'
      preLoaderRoute: typeof AppMethodologyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portfolio': {
      id: '/app/portfolio'
      path: '/portfolio'
      fullPath: '/app/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/swap': {
      id: '/app/swap'
      path: '/swap'
      fullPath: '/app/swap'
      preLoaderRoute: typeof AppSwapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/token': {
      id: '/app/token'
      path: '/token'
      fullPath: '/app/token'
      preLoaderRoute: typeof AppTokenRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trending': {
      id: '/app/trending'
      path: '/trending'
      fullPath: '/app/trending'
      preLoaderRoute: typeof AppTrendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/watchlist': {
      id: '/app/watchlist'
      path: '/watchlist'
      fullPath: '/app/watchlist'
      preLoaderRoute: typeof AppWatchlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/xstocks': {
      id: '/app/xstocks'
      path: '/xstocks'
      fullPath: '/app/xstocks'
      preLoaderRoute: typeof AppXstocksRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/analytics/bridge-event': {
      id: '/api/analytics/bridge-event'
      path: '/api/analytics/bridge-event'
      fullPath: '/api/analytics/bridge-event'
      preLoaderRoute: typeof ApiAnalyticsBridgeEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/swap-event': {
      id: '/api/analytics/swap-event'
      path: '/api/analytics/swap-event'
      fullPath: '/api/analytics/swap-event'
      preLoaderRoute: typeof ApiAnalyticsSwapEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bridge/chains': {
      id: '/api/bridge/chains'
      path: '/api/bridge/chains'
      fullPath: '/api/bridge/chains'
      preLoaderRoute: typeof ApiBridgeChainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bridge/providers': {
      id: '/api/bridge/providers'
      path: '/api/bridge/providers'
      fullPath: '/api/bridge/providers'
      preLoaderRoute: typeof ApiBridgeProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bridge/quote': {
      id: '/api/bridge/quote'
      path: '/api/bridge/quote'
      fullPath: '/api/bridge/quote'
      preLoaderRoute: typeof ApiBridgeQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bridge/status': {
      id: '/api/bridge/status'
      path: '/api/bridge/status'
      fullPath: '/api/bridge/status'
      preLoaderRoute: typeof ApiBridgeStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bridge/tokens': {
      id: '/api/bridge/tokens'
      path: '/api/bridge/tokens'
      fullPath: '/api/bridge/tokens'
      preLoaderRoute: typeof ApiBridgeTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed/new-launches': {
      id: '/api/feed/new-launches'
      path: '/api/feed/new-launches'
      fullPath: '/api/feed/new-launches'
      preLoaderRoute: typeof ApiFeedNewLaunchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed/snapshot': {
      id: '/api/feed/snapshot'
      path: '/api/feed/snapshot'
      fullPath: '/api/feed/snapshot'
      preLoaderRoute: typeof ApiFeedSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/status': {
      id: '/api/market/status'
      path: '/api/market/status'
      fullPath: '/api/market/status'
      preLoaderRoute: typeof ApiMarketStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portfolio/holdings': {
      id: '/api/portfolio/holdings'
      path: '/api/portfolio/holdings'
      fullPath: '/api/portfolio/holdings'
      preLoaderRoute: typeof ApiPortfolioHoldingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swap/price': {
      id: '/api/swap/price'
      path: '/api/swap/price'
      fullPath: '/api/swap/price'
      preLoaderRoute: typeof ApiSwapPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swap/quote': {
      id: '/api/swap/quote'
      path: '/api/swap/quote'
      fullPath: '/api/swap/quote'
      preLoaderRoute: typeof ApiSwapQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swap/resolve-token': {
      id: '/api/swap/resolve-token'
      path: '/api/swap/resolve-token'
      fullPath: '/api/swap/resolve-token'
      preLoaderRoute: typeof ApiSwapResolveTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swap/tokens': {
      id: '/api/swap/tokens'
      path: '/api/swap/tokens'
      fullPath: '/api/swap/tokens'
      preLoaderRoute: typeof ApiSwapTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/agents-hub/': {
      id: '/app/agents-hub/'
      path: '/'
      fullPath: '/app/agents-hub/'
      preLoaderRoute: typeof AppAgentsHubIndexRouteImport
      parentRoute: typeof AppAgentsHubRoute
    }
    '/app/agents-hub/$slug': {
      id: '/app/agents-hub/$slug'
      path: '/$slug'
      fullPath: '/app/agents-hub/$slug'
      preLoaderRoute: typeof AppAgentsHubSlugRouteImport
      parentRoute: typeof AppAgentsHubRoute
    }
    '/app/agents/$slug': {
      id: '/app/agents/$slug'
      path: '/$slug'
      fullPath: '/app/agents/$slug'
      preLoaderRoute: typeof AppAgentsSlugRouteImport
      parentRoute: typeof AppAgentsRoute
    }
    '/app/coin/$coinId': {
      id: '/app/coin/$coinId'
      path: '/coin/$coinId'
      fullPath: '/app/coin/$coinId'
      preLoaderRoute: typeof AppCoinCoinIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/markets/': {
      id: '/app/markets/'
      path: '/'
      fullPath: '/app/markets/'
      preLoaderRoute: typeof AppMarketsIndexRouteImport
      parentRoute: typeof AppMarketsRoute
    }
    '/app/markets/global': {
      id: '/app/markets/global'
      path: '/global'
      fullPath: '/app/markets/global'
      preLoaderRoute: typeof AppMarketsGlobalRouteImport
      parentRoute: typeof AppMarketsRoute
    }
    '/app/markets/hot-searches': {
      id: '/app/markets/hot-searches'
      path: '/hot-searches'
      fullPath: '/app/markets/hot-searches'
      preLoaderRoute: typeof AppMarketsHotSearchesRouteImport
      parentRoute: typeof AppMarketsRoute
    }
    '/app/markets/trending': {
      id: '/app/markets/trending'
      path: '/trending'
      fullPath: '/app/markets/trending'
      preLoaderRoute: typeof AppMarketsTrendingRouteImport
      parentRoute: typeof AppMarketsRoute
    }
    '/app/swap/': {
      id: '/app/swap/'
      path: '/'
      fullPath: '/app/swap/'
      preLoaderRoute: typeof AppSwapIndexRouteImport
      parentRoute: typeof AppSwapRoute
    }
    '/app/token/': {
      id: '/app/token/'
      path: '/'
      fullPath: '/app/token/'
      preLoaderRoute: typeof AppTokenIndexRouteImport
      parentRoute: typeof AppTokenRoute
    }
    '/api/market/coingecko/coins': {
      id: '/api/market/coingecko/coins'
      path: '/api/market/coingecko/coins'
      fullPath: '/api/market/coingecko/coins'
      preLoaderRoute: typeof ApiMarketCoingeckoCoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/coingecko/search': {
      id: '/api/market/coingecko/search'
      path: '/api/market/coingecko/search'
      fullPath: '/api/market/coingecko/search'
      preLoaderRoute: typeof ApiMarketCoingeckoSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/coingecko/trending': {
      id: '/api/market/coingecko/trending'
      path: '/api/market/coingecko/trending'
      fullPath: '/api/market/coingecko/trending'
      preLoaderRoute: typeof ApiMarketCoingeckoTrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/dexscreener/pairs': {
      id: '/api/market/dexscreener/pairs'
      path: '/api/market/dexscreener/pairs'
      fullPath: '/api/market/dexscreener/pairs'
      preLoaderRoute: typeof ApiMarketDexscreenerPairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/dexscreener/search': {
      id: '/api/market/dexscreener/search'
      path: '/api/market/dexscreener/search'
      fullPath: '/api/market/dexscreener/search'
      preLoaderRoute: typeof ApiMarketDexscreenerSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/geckoterminal/networks': {
      id: '/api/market/geckoterminal/networks'
      path: '/api/market/geckoterminal/networks'
      fullPath: '/api/market/geckoterminal/networks'
      preLoaderRoute: typeof ApiMarketGeckoterminalNetworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/gmgn/hot-searches': {
      id: '/api/market/gmgn/hot-searches'
      path: '/api/market/gmgn/hot-searches'
      fullPath: '/api/market/gmgn/hot-searches'
      preLoaderRoute: typeof ApiMarketGmgnHotSearchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/gmgn/trending': {
      id: '/api/market/gmgn/trending'
      path: '/api/market/gmgn/trending'
      fullPath: '/api/market/gmgn/trending'
      preLoaderRoute: typeof ApiMarketGmgnTrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/markets/robinhood/$tokenAddress': {
      id: '/app/markets/robinhood/$tokenAddress'
      path: '/robinhood/$tokenAddress'
      fullPath: '/app/markets/robinhood/$tokenAddress'
      preLoaderRoute: typeof AppMarketsRobinhoodTokenAddressRouteImport
      parentRoute: typeof AppMarketsRoute
    }
    '/app/token/$chainId/$address': {
      id: '/app/token/$chainId/$address'
      path: '/$chainId/$address'
      fullPath: '/app/token/$chainId/$address'
      preLoaderRoute: typeof AppTokenChainIdAddressRouteImport
      parentRoute: typeof AppTokenRoute
    }
    '/api/feed/manual-lookup/$chainId/$address': {
      id: '/api/feed/manual-lookup/$chainId/$address'
      path: '/api/feed/manual-lookup/$chainId/$address'
      fullPath: '/api/feed/manual-lookup/$chainId/$address'
      preLoaderRoute: typeof ApiFeedManualLookupChainIdAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/coingecko/chart/$id': {
      id: '/api/market/coingecko/chart/$id'
      path: '/api/market/coingecko/chart/$id'
      fullPath: '/api/market/coingecko/chart/$id'
      preLoaderRoute: typeof ApiMarketCoingeckoChartIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/coingecko/coin/$id': {
      id: '/api/market/coingecko/coin/$id'
      path: '/api/market/coingecko/coin/$id'
      fullPath: '/api/market/coingecko/coin/$id'
      preLoaderRoute: typeof ApiMarketCoingeckoCoinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/dexscreener/trending/$chainId': {
      id: '/api/market/dexscreener/trending/$chainId'
      path: '/api/market/dexscreener/trending/$chainId'
      fullPath: '/api/market/dexscreener/trending/$chainId'
      preLoaderRoute: typeof ApiMarketDexscreenerTrendingChainIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/geckoterminal/pools/$networkId': {
      id: '/api/market/geckoterminal/pools/$networkId'
      path: '/api/market/geckoterminal/pools/$networkId'
      fullPath: '/api/market/geckoterminal/pools/$networkId'
      preLoaderRoute: typeof ApiMarketGeckoterminalPoolsNetworkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/geckoterminal/trending/$networkId': {
      id: '/api/market/geckoterminal/trending/$networkId'
      path: '/api/market/geckoterminal/trending/$networkId'
      fullPath: '/api/market/geckoterminal/trending/$networkId'
      preLoaderRoute: typeof ApiMarketGeckoterminalTrendingNetworkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/dexscreener/token/$chainId/$address': {
      id: '/api/market/dexscreener/token/$chainId/$address'
      path: '/api/market/dexscreener/token/$chainId/$address'
      fullPath: '/api/market/dexscreener/token/$chainId/$address'
      preLoaderRoute: typeof ApiMarketDexscreenerTokenChainIdAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/geckoterminal/ohlcv/$networkId/$poolAddress': {
      id: '/api/market/geckoterminal/ohlcv/$networkId/$poolAddress'
      path: '/api/market/geckoterminal/ohlcv/$networkId/$poolAddress'
      fullPath: '/api/market/geckoterminal/ohlcv/$networkId/$poolAddress'
      preLoaderRoute: typeof ApiMarketGeckoterminalOhlcvNetworkIdPoolAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/geckoterminal/token/$networkId/$address': {
      id: '/api/market/geckoterminal/token/$networkId/$address'
      path: '/api/market/geckoterminal/token/$networkId/$address'
      fullPath: '/api/market/geckoterminal/token/$networkId/$address'
      preLoaderRoute: typeof ApiMarketGeckoterminalTokenNetworkIdAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAgentsRouteChildren {
  AppAgentsSlugRoute: typeof AppAgentsSlugRoute
}

const AppAgentsRouteChildren: AppAgentsRouteChildren = {
  AppAgentsSlugRoute: AppAgentsSlugRoute,
}

const AppAgentsRouteWithChildren = AppAgentsRoute._addFileChildren(
  AppAgentsRouteChildren,
)

interface AppAgentsHubRouteChildren {
  AppAgentsHubSlugRoute: typeof AppAgentsHubSlugRoute
  AppAgentsHubIndexRoute: typeof AppAgentsHubIndexRoute
}

const AppAgentsHubRouteChildren: AppAgentsHubRouteChildren = {
  AppAgentsHubSlugRoute: AppAgentsHubSlugRoute,
  AppAgentsHubIndexRoute: AppAgentsHubIndexRoute,
}

const AppAgentsHubRouteWithChildren = AppAgentsHubRoute._addFileChildren(
  AppAgentsHubRouteChildren,
)

interface AppMarketsRouteChildren {
  AppMarketsGlobalRoute: typeof AppMarketsGlobalRoute
  AppMarketsHotSearchesRoute: typeof AppMarketsHotSearchesRoute
  AppMarketsTrendingRoute: typeof AppMarketsTrendingRoute
  AppMarketsIndexRoute: typeof AppMarketsIndexRoute
  AppMarketsRobinhoodTokenAddressRoute: typeof AppMarketsRobinhoodTokenAddressRoute
}

const AppMarketsRouteChildren: AppMarketsRouteChildren = {
  AppMarketsGlobalRoute: AppMarketsGlobalRoute,
  AppMarketsHotSearchesRoute: AppMarketsHotSearchesRoute,
  AppMarketsTrendingRoute: AppMarketsTrendingRoute,
  AppMarketsIndexRoute: AppMarketsIndexRoute,
  AppMarketsRobinhoodTokenAddressRoute: AppMarketsRobinhoodTokenAddressRoute,
}

const AppMarketsRouteWithChildren = AppMarketsRoute._addFileChildren(
  AppMarketsRouteChildren,
)

interface AppSwapRouteChildren {
  AppSwapIndexRoute: typeof AppSwapIndexRoute
}

const AppSwapRouteChildren: AppSwapRouteChildren = {
  AppSwapIndexRoute: AppSwapIndexRoute,
}

const AppSwapRouteWithChildren =
  AppSwapRoute._addFileChildren(AppSwapRouteChildren)

interface AppTokenRouteChildren {
  AppTokenIndexRoute: typeof AppTokenIndexRoute
  AppTokenChainIdAddressRoute: typeof AppTokenChainIdAddressRoute
}

const AppTokenRouteChildren: AppTokenRouteChildren = {
  AppTokenIndexRoute: AppTokenIndexRoute,
  AppTokenChainIdAddressRoute: AppTokenChainIdAddressRoute,
}

const AppTokenRouteWithChildren = AppTokenRoute._addFileChildren(
  AppTokenRouteChildren,
)

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRouteWithChildren
  AppAgentsHubRoute: typeof AppAgentsHubRouteWithChildren
  AppAiFeedRoute: typeof AppAiFeedRoute
  AppDataRoute: typeof AppDataRoute
  AppDisclaimerRoute: typeof AppDisclaimerRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMarketsRoute: typeof AppMarketsRouteWithChildren
  AppMethodologyRoute: typeof AppMethodologyRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppSwapRoute: typeof AppSwapRouteWithChildren
  AppTokenRoute: typeof AppTokenRouteWithChildren
  AppTrendingRoute: typeof AppTrendingRoute
  AppWatchlistRoute: typeof AppWatchlistRoute
  AppXstocksRoute: typeof AppXstocksRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCoinCoinIdRoute: typeof AppCoinCoinIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRouteWithChildren,
  AppAgentsHubRoute: AppAgentsHubRouteWithChildren,
  AppAiFeedRoute: AppAiFeedRoute,
  AppDataRoute: AppDataRoute,
  AppDisclaimerRoute: AppDisclaimerRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMarketsRoute: AppMarketsRouteWithChildren,
  AppMethodologyRoute: AppMethodologyRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppSwapRoute: AppSwapRouteWithChildren,
  AppTokenRoute: AppTokenRouteWithChildren,
  AppTrendingRoute: AppTrendingRoute,
  AppWatchlistRoute: AppWatchlistRoute,
  AppXstocksRoute: AppXstocksRoute,
  AppIndexRoute: AppIndexRoute,
  AppCoinCoinIdRoute: AppCoinCoinIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiAnalyticsBridgeEventRoute: ApiAnalyticsBridgeEventRoute,
  ApiAnalyticsSwapEventRoute: ApiAnalyticsSwapEventRoute,
  ApiBridgeChainsRoute: ApiBridgeChainsRoute,
  ApiBridgeProvidersRoute: ApiBridgeProvidersRoute,
  ApiBridgeQuoteRoute: ApiBridgeQuoteRoute,
  ApiBridgeStatusRoute: ApiBridgeStatusRoute,
  ApiBridgeTokensRoute: ApiBridgeTokensRoute,
  ApiFeedNewLaunchesRoute: ApiFeedNewLaunchesRoute,
  ApiFeedSnapshotRoute: ApiFeedSnapshotRoute,
  ApiMarketStatusRoute: ApiMarketStatusRoute,
  ApiPortfolioHoldingsRoute: ApiPortfolioHoldingsRoute,
  ApiSwapPriceRoute: ApiSwapPriceRoute,
  ApiSwapQuoteRoute: ApiSwapQuoteRoute,
  ApiSwapResolveTokenRoute: ApiSwapResolveTokenRoute,
  ApiSwapTokensRoute: ApiSwapTokensRoute,
  ApiMarketCoingeckoCoinsRoute: ApiMarketCoingeckoCoinsRoute,
  ApiMarketCoingeckoSearchRoute: ApiMarketCoingeckoSearchRoute,
  ApiMarketCoingeckoTrendingRoute: ApiMarketCoingeckoTrendingRoute,
  ApiMarketDexscreenerPairsRoute: ApiMarketDexscreenerPairsRoute,
  ApiMarketDexscreenerSearchRoute: ApiMarketDexscreenerSearchRoute,
  ApiMarketGeckoterminalNetworksRoute: ApiMarketGeckoterminalNetworksRoute,
  ApiMarketGmgnHotSearchesRoute: ApiMarketGmgnHotSearchesRoute,
  ApiMarketGmgnTrendingRoute: ApiMarketGmgnTrendingRoute,
  ApiFeedManualLookupChainIdAddressRoute:
    ApiFeedManualLookupChainIdAddressRoute,
  ApiMarketCoingeckoChartIdRoute: ApiMarketCoingeckoChartIdRoute,
  ApiMarketCoingeckoCoinIdRoute: ApiMarketCoingeckoCoinIdRoute,
  ApiMarketDexscreenerTrendingChainIdRoute:
    ApiMarketDexscreenerTrendingChainIdRoute,
  ApiMarketGeckoterminalPoolsNetworkIdRoute:
    ApiMarketGeckoterminalPoolsNetworkIdRoute,
  ApiMarketGeckoterminalTrendingNetworkIdRoute:
    ApiMarketGeckoterminalTrendingNetworkIdRoute,
  ApiMarketDexscreenerTokenChainIdAddressRoute:
    ApiMarketDexscreenerTokenChainIdAddressRoute,
  ApiMarketGeckoterminalOhlcvNetworkIdPoolAddressRoute:
    ApiMarketGeckoterminalOhlcvNetworkIdPoolAddressRoute,
  ApiMarketGeckoterminalTokenNetworkIdAddressRoute:
    ApiMarketGeckoterminalTokenNetworkIdAddressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
